<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Afghanistan' => ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
            'Albania' => ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'],
            'Algeria' => ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
            'Andorra' => ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'La Massana', 'Ordino'],
            'Angola' => ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Namibe'],
            'Argentina' => ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'San Miguel de Tucumán', 'Mar del Plata', 'Salta', 'Santa Fe', 'Santiago del Estero'],
            'Armenia' => ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Abovyan'],
            'Australia' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Darwin'],
            'Austria' => ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn'],
            'Azerbaijan' => ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Nakhchivan'],
            'Bahrain' => ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town'],
            'Bangladesh' => ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Comilla', 'Rangpur', 'Mymensingh', 'Narayanganj'],
            'Belarus' => ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
            'Belgium' => ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst'],
            'Belize' => ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk', 'Dangriga'],
            'Benin' => ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon'],
            'Bolivia' => ['Santa Cruz de la Sierra', 'La Paz', 'Cochabamba', 'Sucre', 'Oruro', 'Potosí', 'Tarija', 'El Alto'],
            'Bosnia and Herzegovina' => ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'],
            'Botswana' => ['Gaborone', 'Francistown', 'Molepolole', 'Maun', 'Serowe'],
            'Brazil' => ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belém', 'Goiânia', 'Guarulhos', 'Campinas', 'São Luís', 'Maceió', 'Natal', 'Teresina', 'Campo Grande', 'João Pessoa'],
            'Brunei' => ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Bangar'],
            'Bulgaria' => ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven'],
            'Burkina Faso' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya'],
            'Burundi' => ['Bujumbura', 'Gitega', 'Ngozi', 'Rumonge', 'Muyinga'],
            'Cambodia' => ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham'],
            'Cameroon' => ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'],
            'Canada' => ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Brampton', 'Mississauga', 'Surrey', 'Laval', 'Halifax', 'London', 'Markham', 'Vaughan', 'Gatineau', 'Longueuil', 'Burnaby'],
            'Central African Republic' => ['Bangui', 'Bimbo', 'Mbaïki', 'Berberati', 'Kaga-Bandoro'],
            'Chad' => ["N'Djamena", 'Moundou', 'Sarh', 'Abéché', 'Kélo'],
            'Chile' => ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta', 'Viña del Mar', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Iquique'],
            'China' => ['Shanghai', 'Beijing', 'Chongqing', 'Tianjin', 'Guangzhou', 'Shenzhen', 'Wuhan', 'Chengdu', 'Dongguan', 'Foshan', 'Nanjing', 'Xian', 'Hangzhou', 'Shenyang', 'Harbin', 'Qingdao', 'Dalian', 'Zhengzhou', 'Shantou', 'Jinan'],
            'Colombia' => ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Manizales'],
            'Congo' => ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Impfondo'],
            'Costa Rica' => ['San José', 'Cartago', 'Alajuela', 'Heredia', 'Liberia', 'Puntarenas', 'Limón'],
            'Croatia' => ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod', 'Pula', 'Sesvete', 'Karlovac', 'Varaždin'],
            'Cuba' => ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo', 'Santa Clara', 'Las Tunas', 'Bayamo'],
            'Cyprus' => ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos'],
            'Czech Republic' => ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec', 'Olomouc', 'Ústí nad Labem', 'České Budějovice'],
            'Denmark' => ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Gentofte', 'Randers', 'Kolding', 'Horsens'],
            'Dominican Republic' => ['Santo Domingo', 'Santiago de los Caballeros', 'San Pedro de Macorís', 'La Romana', 'San Francisco de Macorís', 'Puerto Plata'],
            'DR Congo' => ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Tshikapa', 'Kolwezi', 'Likasi', 'Goma'],
            'Ecuador' => ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala', 'Duran', 'Manta', 'Portoviejo', 'Loja', 'Ambato'],
            'Egypt' => ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'Tanta', 'Asyut', 'Ismailia', 'Fayyum', 'Zagazig'],
            'El Salvador' => ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel', 'Mejicanos'],
            'Estonia' => ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
            'Ethiopia' => ['Addis Ababa', 'Dire Dawa', "Mek'ele", 'Gondar', 'Adama', 'Hawassa', 'Bahir Dar', 'Dessie', 'Jimma', 'Jijiga'],
            'Finland' => ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio'],
            'France' => ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Grenoble', 'Dijon', 'Angers', 'Nîmes', 'Villeurbanne', 'Saint-Étienne', 'Toulon'],
            'Gabon' => ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'],
            'Georgia' => ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Gori', 'Zugdidi'],
            'Germany' => ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden', 'Hanover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster'],
            'Ghana' => ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Sunyani', 'Cape Coast', 'Koforidua', 'Obuasi'],
            'Greece' => ['Athens', 'Thessaloniki', 'Patras', 'Piraeus', 'Heraklion', 'Larissa', 'Volos', 'Rhodes', 'Ioannina', 'Chania'],
            'Guatemala' => ['Guatemala City', 'Villa Nueva', 'Mixco', 'Quetzaltenango', 'Escuintla', 'Chinautla', 'San Juan Sacatepéquez'],
            'Guinea' => ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labé'],
            'Haiti' => ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétionville', 'Croix-des-Bouquets', 'Cap-Haïtien'],
            'Honduras' => ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'El Progreso', 'Choloma', 'Choluteca'],
            'Hungary' => ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár'],
            'India' => ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad', 'Amritsar'],
            'Indonesia' => ['Jakarta', 'Surabaya', 'Bandung', 'Bekasi', 'Medan', 'Tangerang', 'Semarang', 'Depok', 'Palembang', 'Makassar', 'South Tangerang', 'Batam', 'Pekanbaru', 'Bogor', 'Denpasar', 'Padang', 'Malang', 'Samarinda', 'Banjarmasin', 'Pontianak'],
            'Iran' => ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Ahvaz', 'Qom', 'Kermanshah', 'Urmia', 'Rasht', 'Zahedan', 'Hamadan', 'Kerman', 'Arak'],
            'Iraq' => ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Kirkuk', 'Najaf', 'Karbala', 'Nasiriyah', 'Amarah'],
            'Ireland' => ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan'],
            'Israel' => ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beersheba', 'Bnei Brak', 'Holon'],
            'Italy' => ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste', 'Taranto', 'Brescia', 'Prato', 'Parma', 'Modena'],
            'Ivory Coast' => ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'Korhogo', 'San-Pédro', 'Man'],
            'Jamaica' => ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'Mandeville', 'New Kingston'],
            'Japan' => ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kawasaki', 'Kobe', 'Kyoto', 'Saitama', 'Hiroshima', 'Sendai', 'Kitakyushu', 'Chiba', 'Setagaya', 'Sakai', 'Kumamoto', 'Shizuoka', 'Okayama', 'Sagamihara'],
            'Jordan' => ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Wadi as-Sir', 'Aqaba', 'Madaba', 'As-Salt'],
            'Kazakhstan' => ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe', 'Taraz', 'Pavlodar', 'Ust-Kamenogorsk'],
            'Kenya' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Kisii'],
            'Kuwait' => ['Kuwait City', 'Salmiya', 'Hawalli', 'Farwaniya', 'Fahaheel', 'Al Ahmadi'],
            'Kyrgyzstan' => ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok'],
            'Laos' => ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang', 'Xam Neua'],
            'Latvia' => ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils'],
            'Lebanon' => ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Zahle', 'Jounieh'],
            'Libya' => ['Tripoli', 'Benghazi', 'Misrata', 'Bayda', 'Zliten', 'Ajdabiya'],
            'Lithuania' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus'],
            'Luxembourg' => ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'],
            'Madagascar' => ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara'],
            'Malaysia' => ['Kuala Lumpur', 'Klang', 'Johor Bahru', 'Penang', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Kota Kinabalu', 'Kuching', 'Malacca', 'Subang Jaya', 'Kajang', 'Seremban', 'Kota Bharu', 'Alor Setar'],
            'Mali' => ['Bamako', 'Ségou', 'Sikasso', 'Mopti', 'Gao', 'Koutiala'],
            'Malta' => ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Naxxar', 'Żabbar'],
            'Mauritania' => ['Nouakchott', 'Nouadhibou', 'Néma', 'Kaédi', 'Rosso'],
            'Mauritius' => ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes'],
            'Mexico' => ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Zapopan', 'Mérida', 'Guadalupe', 'Chihuahua', 'Acapulco', 'San Luis Potosí', 'Aguascalientes', 'Hermosillo', 'Saltillo', 'Mexicali', 'Culiacán', 'Morelia', 'Querétaro'],
            'Moldova' => ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Rîbnița'],
            'Mongolia' => ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan', 'Mörön'],
            'Morocco' => ['Casablanca', 'Fes', 'Tangier', 'Marrakech', 'Sale', 'Meknes', 'Rabat', 'Oujda', 'Kenitra', 'Agadir', 'Tetouan', 'Safi', 'El Jadida', 'Khouribga', 'Beni Mellal'],
            'Mozambique' => ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Nacala', 'Quelimane'],
            'Myanmar' => ['Naypyidaw', 'Yangon', 'Mandalay', 'Mawlamyine', 'Bago', 'Pathein', 'Monywa'],
            'Nepal' => ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar', 'Birgunj', 'Dharan', 'Bhaktapur'],
            'Netherlands' => ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen', 'Enschede', 'Haarlem', 'Arnhem', 'Zaanstad', 'Haarlemmermeer'],
            'New Zealand' => ['Auckland', 'Christchurch', 'Wellington', 'Hamilton', 'Tauranga', 'Napier-Hastings', 'Dunedin', 'Palmerston North', 'Nelson', 'Rotorua'],
            'Nicaragua' => ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega', 'Estelí'],
            'Niger' => ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez'],
            'Nigeria' => ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Jos', 'Ilorin', 'Oyo', 'Enugu', 'Abeokuta', 'Sokoto', 'Onitsha', 'Warri', 'Kaduna', 'Ogbomoso', 'Owerri'],
            'North Korea' => ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan', 'Sinuiju'],
            'North Macedonia' => ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Ohrid'],
            'Norway' => ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg'],
            'Oman' => ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar', 'Sur', 'Ibri', 'Nizwa'],
            'Pakistan' => ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Quetta', 'Hyderabad', 'Islamabad', 'Sialkot', 'Sargodha', 'Bahawalpur', 'Sukkur', 'Larkana'],
            'Palestine' => ['Gaza', 'Ramallah', 'Hebron', 'Nablus', 'Jenin', 'Tulkarm', 'Qalqilya', 'Jericho'],
            'Panama' => ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'La Chorrera', 'Colón'],
            'Papua New Guinea' => ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen', 'Madang'],
            'Paraguay' => ['Asunción', 'Ciudad del Este', 'Luque', 'San Lorenzo', 'Capiatá', 'Lambaré', 'Limpio', 'Fernando de la Mora'],
            'Peru' => ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Chimbote', 'Huancayo', 'Tacna'],
            'Philippines' => ['Quezon City', 'Manila', 'Davao City', 'Caloocan', 'Cebu City', 'Zamboanga City', 'Antipolo', 'Taguig', 'Pasig', 'Cagayan de Oro', 'Parañaque', 'Valenzuela', 'Dasmariñas', 'Bacoor', 'General Santos'],
            'Poland' => ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice', 'Białystok', 'Gdynia', 'Częstochowa', 'Radom', 'Sosnowiec'],
            'Portugal' => ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra', 'Funchal', 'Vila Nova de Gaia', 'Almada', 'Agualva-Cacém'],
            'Qatar' => ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Khor', 'Al Wakra', 'Mesaieed'],
            'Romania' => ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea', 'Brăila', 'Bacău', 'Arad', 'Pitești', 'Sibiu'],
            'Russia' => ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Nizhny Novgorod', 'Kazan', 'Chelyabinsk', 'Omsk', 'Samara', 'Rostov-on-Don', 'Ufa', 'Krasnoyarsk', 'Voronezh', 'Perm', 'Volgograd', 'Krasnodar', 'Saratov', 'Tyumen', 'Tolyatti', 'Izhevsk'],
            'Rwanda' => ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba'],
            'Saudi Arabia' => ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Buraidah', 'Jubail', 'Khamis Mushait', 'Hail', 'Hofuf', 'Taif', 'Najran', 'Yanbu'],
            'Senegal' => ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Ziguinchor', 'Saint-Louis', 'Mbour'],
            'Serbia' => ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo'],
            'Sierra Leone' => ['Freetown', 'Bo', 'Kenema', 'Koidu', 'Makeni'],
            'Singapore' => ['Singapore'],
            'Slovakia' => ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava'],
            'Slovenia' => ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper'],
            'Somalia' => ['Mogadishu', 'Hargeisa', 'Bosaso', 'Kismayo', 'Marka', 'Berbera'],
            'South Africa' => ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Soweto', 'East London', 'Pietermaritzburg', 'Benoni', 'Tembisa', 'East Rand', 'Vereeniging', 'Bloemfontein', 'Boksburg', 'Welkom'],
            'South Korea' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam', 'Goyang', 'Yongin', 'Bucheon', 'Cheongju', 'Ansan'],
            'South Sudan' => ['Juba', 'Wau', 'Malakal', 'Yei', 'Torit'],
            'Spain' => ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao', 'Alicante', 'Córdoba', 'Valladolid', 'Vigo', 'Gijón', 'Granada', "L'Hospitalet de Llobregat", 'Vitoria-Gasteiz', 'A Coruña', 'Santa Cruz de Tenerife'],
            'Sri Lanka' => ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Jaffna', 'Negombo', 'Kandy', 'Kalmunai', 'Trincomalee', 'Galle'],
            'Sudan' => ['Omdurman', 'Khartoum', 'Khartoum North', 'Port Sudan', 'Kassala', 'Obeid', 'Wad Madani', 'El Fasher'],
            'Sweden' => ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Sollentuna', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping', 'Haninge', 'Umeå', 'Lund', 'Borås'],
            'Switzerland' => ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel/Bienne'],
            'Syria' => ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Deir ez-Zor', 'Raqqa', 'Qamishli', 'Idlib', 'Tartus'],
            'Taiwan' => ['New Taipei', 'Taipei', 'Taoyuan', 'Taichung', 'Tainan', 'Kaohsiung', 'Hsinchu', 'Keelung', 'Chiayi'],
            'Tajikistan' => ['Dushanbe', 'Khujand', 'Kulob', 'Qurghonteppa', 'Istaravshan'],
            'Tanzania' => ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Tanga', 'Zanzibar City', 'Kahama', 'Tabora'],
            'Thailand' => ['Bangkok', 'Samut Prakan', 'Mueang Nonthaburi', 'Udon Thani', 'Chon Buri', 'Chiang Mai', 'Hat Yai', 'Pak Kret', 'Si Racha', 'Phuket', 'Surat Thani', 'Chiang Rai', 'Nakhon Ratchasima', 'Khon Kaen', 'Ubon Ratchathani'],
            'Togo' => ['Lomé', 'Sokodé', 'Kara', 'Palimé', 'Atakpamé'],
            'Tunisia' => ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Bizerte', 'Gabes', 'Ariana', 'Gafsa', 'Monastir'],
            'Turkey' => ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya', 'Kayseri', 'Mersin', 'Diyarbakır', 'Eskişehir', 'Samsun', 'Denizli', 'Adapazarı', 'Malatya', 'Kahramanmaraş', 'Erzurum', 'Van', 'Batman'],
            'Turkmenistan' => ['Ashgabat', 'Turkmenbashi', 'Dasoguz', 'Mary', 'Balkanabat'],
            'Uganda' => ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Bwizibwera', 'Mbale', 'Mukono'],
            'Ukraine' => ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol', 'Luhansk', 'Vinnytsia', 'Makiivka', 'Sevastopol', 'Simferopol'],
            'United Arab Emirates' => ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'],
            'United Kingdom' => ['London', 'Birmingham', 'Leeds', 'Glasgow', 'Sheffield', 'Manchester', 'Edinburgh', 'Liverpool', 'Bristol', 'Cardiff', 'Leicester', 'Sunderland', 'Belfast', 'Bradford', 'Nottingham', 'Newcastle upon Tyne', 'Plymouth', 'Stoke-on-Trent', 'Southampton', 'Reading'],
            'United States' => ['New York City', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Nashville', 'Oklahoma City', 'El Paso', 'Washington DC', 'Boston', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore', 'Milwaukee', 'Albuquerque'],
            'Uruguay' => ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras', 'Rivera', 'Maldonado'],
            'Uzbekistan' => ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus', 'Fergana', "Qo'qon", 'Bukhara', 'Qarshi', 'Jizzax'],
            'Venezuela' => ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'Barcelona', 'Maturín', 'San Cristóbal', 'Cumana'],
            'Vietnam' => ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Bien Hoa', 'Can Tho', 'Hue', 'Nha Trang', 'Long Xuyen', 'Da Lat', 'Rach Gia', 'Quy Nhon', 'Vung Tau', 'My Tho', 'Nam Dinh'],
            'Yemen' => ["Sana'a", 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb', 'Mukalla', 'Dhamār'],
            'Zambia' => ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Livingstone'],
            'Zimbabwe' => ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth', 'Gweru', 'Kwekwe', 'Kadoma'],
        ];

        foreach ($data as $countryName => $cities) {
            $country = Location::updateOrCreate(
                ['name' => $countryName, 'type' => 'country'],
                ['is_active' => true]
            );

            foreach ($cities as $cityName) {
                Location::updateOrCreate(
                    ['name' => $cityName, 'type' => 'city', 'parent_id' => $country->id],
                    ['is_active' => true]
                );
            }
        }
    }
}
