<?php

namespace Database\Seeders;

use App\Models\Policy;
use App\Models\PolicyPlatformAction;
use Illuminate\Database\Seeder;

class PolicySeeder extends Seeder
{
    public function run(): void
    {
        $policies = $this->policyDefinitions();

        foreach ($policies as $data) {
            $actions = $data['platform_actions'] ?? [];
            unset($data['platform_actions']);

            $data['slug'] = Policy::generateSlug($data['title']);
            $data['published_at'] = now();

            $policy = Policy::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );

            // Sync platform actions
            PolicyPlatformAction::where('policy_id', $policy->id)->delete();
            foreach ($actions as $action) {
                PolicyPlatformAction::create([
                    'policy_id' => $policy->id,
                    'action' => $action,
                ]);
            }
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function policyDefinitions(): array
    {
        $placeholder = fn (string $name) => "<h2>$name</h2>\n<p>This policy governs the use of our platform with respect to <strong>$name</strong>. Please read this document carefully before using our services. By accessing or using our platform you agree to be bound by the terms described herein.</p>\n<p>We reserve the right to update this policy at any time. Continued use of the platform following any changes constitutes your acceptance of the revised policy.</p>\n<p>If you have questions about this policy, please contact our legal team at <a href=\"mailto:legal@shopenhood.com\">legal@shopenhood.com</a>.</p>";

        return [
            // ── Core Platform ─────────────────────────────────────────────────────────
            [
                'title' => 'Terms of Service',
                'description' => 'The binding legal agreement between Shopenhood and its users governing use of the platform.',
                'content' => $placeholder('Terms of Service'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => true,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['registration'],
            ],
            [
                'title' => 'Terms of Use',
                'description' => 'Rules and guidelines for accessing and using the Shopenhood platform.',
                'content' => $placeholder('Terms of Use'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => true,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['registration', 'login'],
            ],
            [
                'title' => 'Privacy Policy',
                'description' => 'How we collect, use, store, and protect your personal data.',
                'content' => $placeholder('Privacy Policy'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => true,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['registration'],
            ],
            [
                'title' => 'Cookie Policy',
                'description' => 'Information about how we use cookies and similar tracking technologies.',
                'content' => $placeholder('Cookie Policy'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => true,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['registration'],
            ],
            [
                'title' => 'Acceptable Use Policy',
                'description' => 'Standards of conduct required from all users of the platform.',
                'content' => $placeholder('Acceptable Use Policy'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => true,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['registration'],
            ],
            [
                'title' => 'Platform Rules',
                'description' => 'Core rules all users must follow when using Shopenhood.',
                'content' => $placeholder('Platform Rules'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Community Guidelines',
                'description' => 'Standards for respectful and constructive behaviour within the Shopenhood community.',
                'content' => $placeholder('Community Guidelines'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Disclaimer',
                'description' => 'Limitations of liability and disclaimers regarding platform content and transactions.',
                'content' => $placeholder('Disclaimer'),
                'policy_type' => 'core',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],

            // ── Marketplace & Vendor ──────────────────────────────────────────────────
            [
                'title' => 'Seller Agreement',
                'description' => 'Legal agreement between Shopenhood and all sellers operating on the platform.',
                'content' => $placeholder('Seller Agreement'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['product_listing'],
            ],
            [
                'title' => 'Vendor Terms',
                'description' => 'Terms and conditions governing vendor accounts and business operations.',
                'content' => $placeholder('Vendor Terms'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['product_listing'],
            ],
            [
                'title' => 'Product Listing Policy',
                'description' => 'Rules and requirements for creating and managing product listings on the platform.',
                'content' => $placeholder('Product Listing Policy'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['product_listing', 'auction_creation'],
            ],
            [
                'title' => 'Marketplace Rules',
                'description' => 'Comprehensive rules governing all marketplace activity on Shopenhood.',
                'content' => $placeholder('Marketplace Rules'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Commission Policy',
                'description' => 'Details of platform fees, commissions, and revenue sharing arrangements.',
                'content' => $placeholder('Commission Policy'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Vendor Verification Policy',
                'description' => 'Requirements and procedures for vendor identity and business verification.',
                'content' => $placeholder('Vendor Verification Policy'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Vendor Conduct Policy',
                'description' => 'Expected standards of conduct and professionalism required from all vendors.',
                'content' => $placeholder('Vendor Conduct Policy'),
                'policy_type' => 'marketplace_vendor',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],

            // ── Transaction ───────────────────────────────────────────────────────────
            [
                'title' => 'Payment Policy',
                'description' => 'Accepted payment methods, processing times, and payment security practices.',
                'content' => $placeholder('Payment Policy'),
                'policy_type' => 'transaction',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => true,
                'show_during_listing' => false,
                'platform_actions' => ['checkout', 'purchase'],
            ],
            [
                'title' => 'Billing Policy',
                'description' => 'How and when users and vendors are billed for platform services.',
                'content' => $placeholder('Billing Policy'),
                'policy_type' => 'transaction',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Refund Policy',
                'description' => 'Eligibility criteria and procedures for requesting refunds.',
                'content' => $placeholder('Refund Policy'),
                'policy_type' => 'transaction',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => true,
                'show_during_listing' => false,
                'platform_actions' => ['checkout'],
            ],
            [
                'title' => 'Return Policy',
                'description' => 'Guidelines for returning purchased products and obtaining replacements or refunds.',
                'content' => $placeholder('Return Policy'),
                'policy_type' => 'transaction',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => true,
                'show_during_listing' => false,
                'platform_actions' => ['checkout'],
            ],
            [
                'title' => 'Chargeback Policy',
                'description' => 'How we handle payment disputes, chargebacks, and fraudulent transactions.',
                'content' => $placeholder('Chargeback Policy'),
                'policy_type' => 'transaction',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],

            // ── Trading Models ────────────────────────────────────────────────────────
            [
                'title' => 'Sale Terms',
                'description' => 'Terms governing standard buy/sell transactions on the platform.',
                'content' => $placeholder('Sale Terms'),
                'policy_type' => 'trading',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => true,
                'show_during_listing' => false,
                'platform_actions' => ['checkout', 'purchase'],
            ],
            [
                'title' => 'Barter / Trade Policy',
                'description' => 'Rules and procedures governing product exchange and barter transactions.',
                'content' => $placeholder('Barter / Trade Policy'),
                'policy_type' => 'trading',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['barter_request'],
            ],
            [
                'title' => 'Gift Transfer Policy',
                'description' => 'Terms for gifting products or transferring ownership without monetary exchange.',
                'content' => $placeholder('Gift Transfer Policy'),
                'policy_type' => 'trading',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['gift_transfer'],
            ],
            [
                'title' => 'Auction Terms',
                'description' => 'Terms governing all auction listings created on the platform.',
                'content' => $placeholder('Auction Terms'),
                'policy_type' => 'trading',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['auction_creation', 'product_listing'],
            ],
            [
                'title' => 'Auction Bidding Rules',
                'description' => 'Rules and obligations for bidders participating in platform auctions.',
                'content' => $placeholder('Auction Bidding Rules'),
                'policy_type' => 'trading',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['auction_bidding'],
            ],
            [
                'title' => 'Auction Settlement Policy',
                'description' => 'How auction results are finalised and obligations of winning bidders.',
                'content' => $placeholder('Auction Settlement Policy'),
                'policy_type' => 'trading',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],

            // ── Shipping & Logistics ──────────────────────────────────────────────────
            [
                'title' => 'Shipping Policy',
                'description' => 'General rules and timelines governing product shipment on Shopenhood.',
                'content' => $placeholder('Shipping Policy'),
                'policy_type' => 'shipping',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => true,
                'show_during_listing' => false,
                'platform_actions' => ['checkout'],
            ],
            [
                'title' => 'Delivery Policy',
                'description' => 'Terms for product delivery, estimated timelines, and carrier responsibilities.',
                'content' => $placeholder('Delivery Policy'),
                'policy_type' => 'shipping',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'International Shipping Policy',
                'description' => 'Rules and restrictions governing cross-border shipments.',
                'content' => $placeholder('International Shipping Policy'),
                'policy_type' => 'shipping',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Customs & Import Responsibility Policy',
                'description' => 'Buyer and seller responsibilities for customs duties, taxes, and import restrictions.',
                'content' => $placeholder('Customs & Import Responsibility Policy'),
                'policy_type' => 'shipping',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],

            // ── Product & Content Rules ───────────────────────────────────────────────
            [
                'title' => 'Prohibited Products Policy',
                'description' => 'Products and items that are strictly forbidden from being listed on the platform.',
                'content' => $placeholder('Prohibited Products Policy'),
                'policy_type' => 'product_content',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['product_listing', 'auction_creation'],
            ],
            [
                'title' => 'Restricted Products Policy',
                'description' => 'Products that require special approval or documentation before listing.',
                'content' => $placeholder('Restricted Products Policy'),
                'policy_type' => 'product_content',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['product_listing'],
            ],
            [
                'title' => 'Intellectual Property Policy',
                'description' => 'Protection and enforcement of intellectual property rights on the platform.',
                'content' => $placeholder('Intellectual Property Policy'),
                'policy_type' => 'product_content',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Copyright Policy',
                'description' => 'Rules governing use of copyrighted material in listings and on the platform.',
                'content' => $placeholder('Copyright Policy'),
                'policy_type' => 'product_content',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Counterfeit Goods Policy',
                'description' => 'Zero-tolerance approach to counterfeit, fake, or misleadingly described goods.',
                'content' => $placeholder('Counterfeit Goods Policy'),
                'policy_type' => 'product_content',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => true,
                'platform_actions' => ['product_listing'],
            ],

            // ── Safety & Compliance ───────────────────────────────────────────────────
            [
                'title' => 'Data Protection Policy',
                'description' => 'How personal data is protected in compliance with applicable data protection laws.',
                'content' => $placeholder('Data Protection Policy'),
                'policy_type' => 'safety_compliance',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Data Processing Agreement',
                'description' => 'DPA governing how we process personal data on behalf of vendors and business users.',
                'content' => $placeholder('Data Processing Agreement'),
                'policy_type' => 'safety_compliance',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'GDPR Compliance Notice',
                'description' => 'Notice to EU users regarding their rights under the General Data Protection Regulation.',
                'content' => $placeholder('GDPR Compliance Notice'),
                'policy_type' => 'safety_compliance',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Security Policy',
                'description' => 'Platform security practices, vulnerability disclosure, and incident response.',
                'content' => $placeholder('Security Policy'),
                'policy_type' => 'safety_compliance',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Fraud Prevention Policy',
                'description' => 'Measures to detect, prevent, and respond to fraudulent activity on the platform.',
                'content' => $placeholder('Fraud Prevention Policy'),
                'policy_type' => 'safety_compliance',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => false,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],

            // ── Dispute & Legal ───────────────────────────────────────────────────────
            [
                'title' => 'Dispute Resolution Policy',
                'description' => 'Procedures for resolving disputes between buyers, sellers, and the platform.',
                'content' => $placeholder('Dispute Resolution Policy'),
                'policy_type' => 'dispute_legal',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Buyer Protection Policy',
                'description' => 'Protections and remedies available to buyers in case of problems with orders.',
                'content' => $placeholder('Buyer Protection Policy'),
                'policy_type' => 'dispute_legal',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Seller Protection Policy',
                'description' => 'Protections available to sellers against fraudulent buyers and unjust chargebacks.',
                'content' => $placeholder('Seller Protection Policy'),
                'policy_type' => 'dispute_legal',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
            [
                'title' => 'Arbitration Agreement',
                'description' => 'Agreement to resolve legal disputes through binding arbitration rather than litigation.',
                'content' => $placeholder('Arbitration Agreement'),
                'policy_type' => 'dispute_legal',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => true,
                'show_in_footer' => false,
                'show_during_registration' => true,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => ['registration'],
            ],
            [
                'title' => 'Complaint Policy',
                'description' => 'How to submit a formal complaint and the process we follow to address it.',
                'content' => $placeholder('Complaint Policy'),
                'policy_type' => 'dispute_legal',
                'version' => '1.0',
                'status' => 'active',
                'require_acceptance' => false,
                'show_in_footer' => true,
                'show_during_registration' => false,
                'show_during_checkout' => false,
                'show_during_listing' => false,
                'platform_actions' => [],
            ],
        ];
    }
}
